// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2amOzPwhJDnPcJOqHTJexbhEDtiv4bM0',
    appId: '1:308814908368:android:57e55c0b0db45eebc5c7d5',
    messagingSenderId: '308814908368',
    projectId: 'spa-flutter-app-ed4a8',
    storageBucket: 'spa-flutter-app-ed4a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfN11jelmyZAbqynmoe3cQY2-AC_sgZzs',
    appId: '1:308814908368:ios:95cc1a5a31fc2556c5c7d5',
    messagingSenderId: '308814908368',
    projectId: 'spa-flutter-app-ed4a8',
    storageBucket: 'spa-flutter-app-ed4a8.appspot.com',
    iosClientId: '308814908368-dvhq05284suq0qc43tmnokmoa4b2mpq2.apps.googleusercontent.com',
    iosBundleId: 'com.studentpersonalassistant.studentPersonalAssistant',
  );
}
